#! /bin/bash

set -euo pipefail

cmd="$(basename "$0")"
full_cmd="$0"
modules_dir="/opt/scripts/sysadm-cmd/modules"
functions_dir="$modules_dir/functions"

source $modules_dir/main.shm
source $modules_dir/formatting.shm

version() {
	cat<<-EOF
	SYSADM-CMD CLI version v$VERSION	
	EOF
	exit
}

oneline_usage="usage: $cmd [-v] [-m] COMMAND ..."

usage() { 
	cat<<-EOF
		$oneline_usage
		for more details, run:	$cmd -h
	EOF
	exit
}

longhelp() {
	echo -e "${BOLD}$oneline_usage${RESET}"
	echo
	echo "optional arguments:"
	echo "  -h, --help     show this help message and exit"
    echo "  -v, --version  show program's version number and exit"
    echo 
	echo   "commands:"
	echo_f "${BOLD}" "  check" "     Check host(s) system information, eg. uptime, users, cpucores, mem, etc."
	echo_f "${BOLD}" "  modify" "    Modify host(s) specified system configuration."
	echo_f "${BOLD}" "  install" "   Install specified package(s) to the designated host(s)."
	echo_f "${BOLD}" "  remove" "    Remove specified package(s) from the designated host(s)."
	echo
	echo "to get more details for each command, run: $cmd COMMAND --help"
	echo
	echo "$cmd is a command line tool for systems administrator to manage multiple remote servers."
	echo "You should already have your public ssh keys in your target server otherwise, you'll be prompted for password every step."
	echo "repository: github.com/annahri/sysadm-cmd"
}

main() {
	# If no args given
	[ $# -eq 0 ] && usage

	operation="$1"
	shift

	case $operation in
		-h|--help) longhelp ;;
		-v|--version) version ;;
		-m|--modules) list_modules ;;
		add|a) action_add "$@" ;;
		check|ch|c) action_check "$@" ;;
		install|it|i) action_install "$@" ;;
		remove|rm|r) action_remove "$@" ;;
		*) msg_error "Unknown operation $operation" ;;
	esac
}
	
main "$@"
